version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./mongodb_data:/data/db

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
